services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: "community-database"
    restart: unless-stopped
    volumes:
      - db_community:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - community_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 40s
      retries: 8

  community-service-discovery:
    build: ./community-service-discovery
    ports:
      - "8761:8761"
    container_name: "community-service-discovery"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - community_net

  community-api-gateway:
    build: ./community-api-gateway
    ports:
      - "8080:8080"
    container_name: "community-api-gateway"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - community_net
    depends_on:
      - community-service-discovery

  community-user-service:
    build: ./community-user-service
    ports:
      - "8081:8081"
    container_name: "community-user-service"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/Sao_Paulo"
    env_file:
      - path: ./jwt.env
        required: true
    networks:
      - community_net
    restart: always
    depends_on:
      community-service-discovery:
        condition: service_started
      community-api-gateway:
        condition: service_started
      database:
        condition: service_healthy

  community-upload-service:
    build: ./community-upload-service
    ports:
      - "8083:8083"
    container_name: "community-upload-service"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - community_net
    restart: always
    depends_on:
      community-service-discovery:
        condition: service_started
      community-api-gateway:
        condition: service_started
      database:
        condition: service_healthy

  community-post-service:
    build: ./community-post-service
    ports:
      - "8082:8082"
    container_name: "community-post-service"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/Sao_Paulo"
    networks:
      - community_net
    restart: always
    depends_on:
      community-service-discovery:
        condition: service_started
      community-api-gateway:
        condition: service_started
      database:
        condition: service_healthy

networks:
  community_net:
    driver: bridge
    name: "community_net"

volumes:
  db_community:
    name: "db_community"
